export type Locale = 'pt' | 'en'

const sharedProjects = [
  ['bianca-saboia', 'Bianca Saboia', 'Beauty', 'https://clinicabiancasaboia.vercel.app', 'rose', '/projects/bianca-saboia.png'],
  ['soulzen', 'Soulzen', 'Wellness', 'https://soulzen-three.vercel.app', 'sage', '/projects/soulzen.png'],
  ['login-laser-tag', 'Login Laser Tag', 'Entertainment', 'https://loginlasertag.vercel.app', 'laser', '/projects/login-laser-tag.png'],
  ['hotel-umu', 'Hotel Umu', 'Hospitality', 'https://hotel-umu-demonstracao.vercel.app', 'gold', '/projects/hotel-umu.png'],
  ['casa-da-alcacova', 'Casa da Alcáçova', 'Hospitality', 'https://casa-de-alcacova-demonstracao.vercel.app', 'stone', '/projects/casa-da-alcacova.png'],
]

export const content = {
pt: {
  seo:{title:'Kovelo Studio — Desenvolvimento Web & Experiências Digitais',description:'Kovelo Studio cria websites e experiências digitais à medida, combinando design, desenvolvimento, performance e tecnologia.'},
  nav:{home:'Início',services:'Serviços',projects:'Projetos',about:'Sobre nós',contact:'Contacto',start:'Começar um projeto',menu:'Abrir menu',language:'Alterar idioma'},
  common:{studio:'Experiências digitais',viewWork:'Ver projetos',viewProject:'Ver projeto',live:'Projeto ao vivo',caseStudies:'Estudos de caso',back:'Voltar',next:'Continuar',previous:'Voltar',edit:'Editar respostas',explore:'Explorar serviços',all:'Todos'},
  home:{hero:'Código com visão.|Design com impacto.',intro:'Desenvolvemos experiências digitais à medida para marcas que querem destacar-se.',tags:['Desenvolvimento web','UI / UX','Performance','SEO','Experiência digital'],manifesto:'Não criamos apenas websites.|Criamos experiências digitais.',manifestoCopy:'Acreditamos que um website deve comunicar, envolver e transformar a forma como uma marca é percebida. Unimos estratégia, design e desenvolvimento para criar experiências rápidas, memoráveis e feitas à medida.',servicesLabel:'O que construímos',work:'Projetos selecionados.',workCopy:'Projetos reais. Experiências construídas à medida.',difference:'Precisão por|design.',playground:'Isto não é|um template.',playCopy:'Explore. Cada interação tem uma intenção.',cta:'Pronto para criar|o que vem a seguir?',ctaCopy:'Vamos transformar a sua próxima ideia numa experiência digital.'},
  services:{hero:'Construímos|para a web.',intro:'Design, tecnologia e estratégia reunidos numa experiência digital construída para o seu negócio.',items:[['Desenvolvimento web à medida','Sites desenvolvidos à medida, sem depender de templates genéricos.'],['UI / UX design','Interfaces bonitas, intuitivas e fáceis de utilizar.'],['Performance & SEO','Experiências rápidas, tecnicamente sólidas e preparadas para pesquisa.'],['Manutenção & suporte','Continuamos presentes depois do lançamento.']]},
  process:{label:'Como construímos',title:'Da intenção|ao impacto.',items:[['Descobrir','Entendemos o negócio, público e objetivos.'],['Desenhar','Criamos a experiência visual e a estrutura.'],['Desenvolver','Transformamos o conceito em produto digital.'],['Lançar','Testamos, otimizamos e colocamos no ar.']]},
  pillars:[['Performance','Experiências rápidas e otimizadas.'],['SEO','Estrutura preparada para ser encontrada.'],['Design à medida','Cada projeto começa do zero.'],['Segurança','Boas práticas até ao lançamento.']],
  projects:{hero:'Projetos|selecionados.',intro:'Projetos reais. Experiências construídas à medida.',filters:['Todos','Beauty','Wellness','Entertainment','Hospitality'],descriptions:['Experiência digital para uma marca de estética avançada, combinando serviços, autoridade e conversão.','Uma experiência digital centrada em bem-estar, apresentação do espaço, serviços e marcação.','Uma experiência digital criada para uma marca de entretenimento, com impacto visual e ação.','Experiência digital para hotelaria, criada para apresentar o espaço e facilitar a descoberta.','Uma experiência digital inspirada na identidade histórica e na atmosfera da Casa da Alcáçova.'],detail:'Visão geral do projeto',detailCopy:'Uma experiência digital personalizada, construída para comunicar a identidade da marca com clareza e intenção.'},
  contact:{hero:'Vamos construir|algo.',intro:'Conte-nos um pouco sobre o seu projeto. Queremos perceber o seu negócio, os seus objetivos e o que pretende construir.',steps:['Sobre si','Projeto','Investimento','Prazo','Revisão'],about:'Primeiro, fale-nos sobre si.',name:'Nome completo',email:'E-mail profissional',company:'Empresa / projeto',website:'Website atual',aboutHint:'Se já possui um website, podemos analisá-lo antes da nossa conversa.',project:'O que vamos construir?',projectQuestion:'Qual é o principal objetivo deste projeto?',projectTypes:['Criar um website de raiz','Redesign / atualização de website','E-commerce','Landing page de alta conversão','Outro'],description:'Fale-nos sobre o seu projeto',placeholder:'Conte-nos sobre o seu negócio, o que pretende melhorar e o que gostaria que o novo website fizesse por si...',investment:'Vamos falar de investimento.',investmentCopy:'Esta informação ajuda-nos a preparar uma proposta adequada ao que pretende construir.',budgetQuestion:'Qual é o orçamento estimado?',budgets:['Menos de €1.000','€1.000 – €2.500','€2.500 – €5.000','Mais de €5.000'],timeline:'Quando quer lançar?',timelineQuestion:'Qual é o prazo ideal?',timelines:['O mais rapidamente possível','Dentro de 1–2 meses','Mais de 2 meses / sem urgência','Ainda não tenho uma data'],review:'O seu projeto.',submit:'Solicitar Diagnóstico Gratuito',required:'Este campo é obrigatório.',invalidEmail:'Introduza um e-mail válido.',select:'Selecione uma opção.',unconfigured:'Adicione a chave de acesso em VITE_WEB3FORMS_ACCESS_KEY para ativar o envio do formulário.',failed:'Não foi possível enviar o formulário. Verifique os seus dados e tente novamente.'},
  thanks:{title:'Projeto|recebido.',body:'Obrigado por entrar em contacto com a Kovelo Studio. Recebemos as informações do seu projeto e vamos analisá-las.',next:'Quer acelerar o processo? Agende uma conversa rápida com a nossa equipa.',book:'Agendar uma conversa',pending:'O link de agendamento será disponibilizado em breve.'},
  about:{hero:'Não somos apenas|mais um estúdio.',intro:'A KOVELO é um estúdio digital independente. Unimos estratégia, design e desenvolvimento web para tornar o valor de uma marca claro, credível e difícil de confundir.',originLabel:'Porque existimos',originTitle:'Há valor que o digital não revela.',originCopy:'Um website pode funcionar e, ainda assim, deixar por dizer o que torna um negócio distinto. Quando faltam clareza, personalidade ou confiança, a experiência não faz justiça ao que existe por trás. Trabalhamos no intervalo entre o que uma marca é e aquilo que as pessoas conseguem perceber.',designTitle:'Design',designCopy:'Dá forma à perceção. Organiza a mensagem e orienta cada interação; não é decoração, é como a marca se torna compreensível.',developmentTitle:'Development',developmentCopy:'Torna a experiência real. Design e desenvolvimento influenciam-se mutuamente, sempre guiados pelo objetivo do projeto.',fit:'Por trás de cada projeto há pessoas a ouvir, pensar e construir. Trabalhamos melhor com quem valoriza identidade, experiência e cuidado — e não quer apenas estar online.',valuesLabel:'Como trabalhamos',values:[['Compreender antes de criar','Começamos pelo negócio, o objetivo, as pessoas e o contexto. Primeiro alinhamos o que importa; depois estruturamos a experiência.'],['Decidir com intenção','Cada escolha visual e técnica serve um propósito. A tecnologia entra para melhorar a experiência, não para chamar a atenção para si.'],['Refinar em diálogo','Criamos, desenvolvemos, testamos e ajustamos com atenção aos detalhes. As decisões são explicadas e o objetivo mantém-se à vista.']],foundersLabel:'Quem está por trás',foundersTitle:'Duas perspetivas.|Um só estúdio.',foundersIntro:'A KOVELO é uma parceria. Thainá e João trazem contributos diferentes, mas participam juntos nas decisões, no desenvolvimento dos projetos e no acompanhamento dos clientes.',founders:[{name:'Thainá Oliveira',role:'Direção criativa e comunicação',contribution:'Participa na definição da identidade visual, da experiência, do conteúdo e da apresentação dos projetos. Está nas conversas com os clientes para apresentar as ideias e a visão da KOVELO.',image:''},{name:'João Freitas',role:'Estratégia comercial e negociação',contribution:'Participa na definição das propostas, conduz a vertente comercial das reuniões e envolve-se na negociação e no fecho dos projetos.',image:''}],foundersClose:'Não são áreas isoladas. Os dois participam no desenvolvimento, nas decisões estratégicas e no acompanhamento de cada cliente.',ctaTitle:'Vamos dar forma|ao que vem a seguir.',ctaCopy:'Se o seu digital ainda não mostra o valor do seu negócio, conversemos sobre o que pode mudar.'},
  footer:'Experiências digitais, construídas de forma diferente.',
  copyright:'© 2026 KOVELO STUDIO. Todos os direitos reservados.'
},
en: {
  seo:{title:'Kovelo Studio — Web Development & Digital Experiences',description:'Kovelo Studio creates custom websites and digital experiences through design, development, performance and technology.'},
  nav:{home:'Home',services:'Services',projects:'Projects',about:'About',contact:'Contact',start:'Start a project',menu:'Open menu',language:'Change language'},
  common:{studio:'Digital experiences',viewWork:'View our work',viewProject:'View project',live:'Live project',caseStudies:'Case studies',back:'Back',next:'Continue',previous:'Back',edit:'Edit answers',explore:'Explore services',all:'All'},
  home:{hero:'Code with vision.|Design with impact.',intro:'We build custom digital experiences for brands that want to stand out.',tags:['Web development','UI / UX','Performance','SEO','Digital experience'],manifesto:"We don't just build websites.|We build digital experiences.",manifestoCopy:'A website should communicate, engage and reshape how a brand is perceived. We bring strategy, design and development together to build fast, memorable experiences with purpose.',servicesLabel:'What we build',work:'Selected work.',workCopy:'Real projects. Custom-built experiences.',difference:'Precise by|design.',playground:'This is not|a template.',playCopy:'Move through it. Every interaction has an intention.',cta:"Ready to build|what's next?",ctaCopy:"Let's turn your next idea into a digital experience."},
  services:{hero:'We build|for the web.',intro:'Design, technology and strategy brought together in a digital experience built around your business.',items:[['Custom web development','Websites made to measure, never dependent on generic templates.'],['UI / UX design','Interfaces that are striking, intuitive and easy to use.'],['Performance & SEO','Fast, technically sound experiences prepared for search.'],['Maintenance & support','We stay involved after launch to keep everything working well.']]},
  process:{label:'How we build',title:'From intent|to impact.',items:[['Discover','We understand the business, audience and objectives.'],['Design','We shape the visual experience and structure.'],['Build','We turn the concept into a digital product.'],['Launch','We test, optimise and put it live.']]},
  pillars:[['Performance','Fast, optimised experiences.'],['SEO','A structure prepared to be found.'],['Custom design','Every project starts from zero.'],['Security','Good practice from build to launch.']],
  projects:{hero:'Selected|work.',intro:'Real projects. Custom-built experiences.',filters:['All','Beauty','Wellness','Entertainment','Hospitality'],descriptions:['A digital experience for an advanced aesthetics brand, combining services, authority and conversion.','A wellness-led digital experience built around the space, services and booking journey.','A digital experience for an entertainment brand, focused on visual impact and action.','A hospitality experience designed to present the space and make the hotel easier to discover.','A digital experience inspired by the historic identity and atmosphere of Casa da Alcáçova.'],detail:'Project overview',detailCopy:'A tailored digital experience, designed to express the brand identity with clarity and intention.'},
  contact:{hero:"Let's build|something.",intro:'Tell us about your project. We want to understand your business, your goals and what you want to build.',steps:['About you','Project','Investment','Timeline','Review'],about:'First, tell us about you.',name:'Full name',email:'Professional email',company:'Company / project',website:'Current website',aboutHint:'If you already have a website, we can review it before our conversation.',project:'What are we building?',projectQuestion:'What is the main goal for this project?',projectTypes:['Build a website from scratch','Redesign / update an existing website','E-commerce','High-converting landing page','Other'],description:'Tell us about your project',placeholder:'Tell us about your business, what you would like to improve and what the new website should do for you...',investment:"Let's talk investment.",investmentCopy:'This helps us prepare a proposal that suits what you want to build.',budgetQuestion:'What is your estimated budget?',budgets:['Less than €1,000','€1,000 – €2,500','€2,500 – €5,000','More than €5,000'],timeline:'When do you want to launch?',timelineQuestion:'What is your ideal timeline?',timelines:['As soon as possible','Within 1–2 months','More than 2 months / no rush',"I don't have a date yet"],review:'Your project.',submit:'Request a Free Diagnosis',required:'This field is required.',invalidEmail:'Enter a valid email address.',select:'Please select an option.',unconfigured:'Add your access key to VITE_WEB3FORMS_ACCESS_KEY to enable form submissions.',failed:'We could not send the form. Check your details and try again.'},
  thanks:{title:'Project|received.',body:'Thank you for trusting Kovelo Studio. We have received your project details and will review them before our conversation.',next:'Want to take the next step now?',book:'Book a 15-minute call',pending:'The booking link will be available soon.'},
  about:{hero:'Not just another|digital studio.',intro:'KOVELO is an independent digital studio. We bring strategy, design and web development together to make a brand’s value clear, credible and hard to confuse.',originLabel:'Why we exist',originTitle:'Some brands have value their digital presence fails to show.',originCopy:'A website can work and still leave out what makes a business distinct. When clarity, personality or trust are missing, the experience falls short of what is behind it. We work in the space between what a brand is and what people are able to perceive.',designTitle:'Design',designCopy:'Shapes perception. It organises the message and guides each interaction; it is not decoration, but how a brand becomes clear.',developmentTitle:'Development',developmentCopy:'Makes the experience real. Design and development shape one another, guided by the project’s purpose.',fit:'Behind every project are people listening, thinking and building. We work best with those who value identity, experience and care — and want more than simply being online.',valuesLabel:'How we work',values:[['Understand before creating','We begin with the business, its goal, its people and its context. First we align on what matters; then we shape the experience.'],['Make intentional decisions','Every visual and technical choice serves a purpose. Technology is there to improve the experience, not draw attention to itself.'],['Refine together','We create, develop, test and adjust with care for the details. Decisions are explained, and the goal stays in view.']],foundersLabel:'Behind KOVELO',foundersTitle:'Two perspectives.|One KOVELO.',foundersIntro:'KOVELO is a partnership. Thainá and João bring different contributions, while sharing decisions, project development and client relationships.',founders:[{name:'Thainá Oliveira',role:'Creative direction and communication',contribution:'Together, she shapes each project’s visual identity, experience, content and presentation. She takes part in client conversations and shares KOVELO’s ideas and vision.',image:''},{name:'João Freitas',role:'Commercial strategy and negotiation',contribution:'He helps shape proposals, leads the commercial side of client meetings and takes part in project negotiations.',image:''}],foundersClose:'These are not separate departments. Both take part in development, strategic decisions and supporting each client.',ctaTitle:'Let’s shape|what comes next.',ctaCopy:'If your digital presence does not yet show your business’s value, let’s talk about what could change.'},
  footer:'Digital experiences, built differently.',
  copyright:'© 2026 KOVELO STUDIO. All rights reserved.'
}}

export const projectBase = sharedProjects

export const caseStudies = {
  pt: [
    { niche:'Estética avançada', objective:'Transformar cuidado especializado numa presença serena, clara e credível.', challenge:'Era essencial apresentar tratamentos e autoridade sem perder a sensação humana do atendimento.', approach:'Criámos uma jornada editorial que organiza serviços, reforça confiança e conduz naturalmente ao contacto.' },
    { niche:'Wellness & beauty', objective:'Dar ao bem-estar um espaço digital tão calmo quanto a experiência presencial.', challenge:'O desafio era tornar serviços e momentos de autocuidado fáceis de descobrir, sem tornar a marca fria.', approach:'A direção combinou ritmo suave, narrativa visual e caminhos simples para explorar e marcar.' },
    { niche:'Entretenimento', objective:'Fazer a energia da arena ser sentida antes mesmo da primeira reserva.', challenge:'A proposta precisava ser compreendida em segundos e transformar curiosidade em vontade de participar.', approach:'Usámos contraste, ritmo e informação direta para levar a experiência da tela à ação.' },
    { niche:'Hotelaria', objective:'Apresentar o hotel como ponto de partida para descobrir Santarém.', challenge:'Era importante unir atmosfera, localização e decisões práticas num só percurso digital.', approach:'Criámos uma experiência acolhedora, com hierarquia clara e uma descoberta visual guiada.' },
    { niche:'Hospitality & heritage', objective:'Traduzir a memória e a presença da Casa da Alcáçova para o digital.', challenge:'O espaço precisava manter a sua identidade histórica sem parecer distante ou estático.', approach:'A narrativa editorial aproxima património, estadia e território numa experiência contemporânea.' }
  ],
  en: [
    { niche:'Advanced aesthetics', objective:'Turn specialist care into a calm, clear and credible digital presence.', challenge:'The experience needed to present treatments and authority without losing the human side of care.', approach:'We shaped an editorial journey that organises services, builds confidence and leads naturally to contact.' },
    { niche:'Wellness & beauty', objective:'Give wellbeing a digital space as calm as the in-person experience.', challenge:'Services and self-care moments had to be easy to discover without making the brand feel cold.', approach:'The direction combines a gentle rhythm, visual storytelling and simple paths to explore and book.' },
    { niche:'Entertainment', objective:'Make the arena energy felt before a visitor makes a reservation.', challenge:'The proposition needed to be understood in seconds and turn curiosity into participation.', approach:'Contrast, rhythm and direct information move the experience from screen to action.' },
    { niche:'Hospitality', objective:'Present the hotel as a starting point for discovering Santarém.', challenge:'Atmosphere, location and practical decisions needed to work together in a single digital journey.', approach:'We created a welcoming experience with clear hierarchy and guided visual discovery.' },
    { niche:'Hospitality & heritage', objective:'Translate Casa da Alcáçova’s history and presence into a digital experience.', challenge:'The space needed to preserve its historic identity without feeling distant or static.', approach:'Editorial storytelling brings heritage, stay and place together in a contemporary experience.' }
  ]
}
