export type Locale = 'pt' | 'en'

const sharedProjects = [
  ['bianca-saboia', 'Bianca Saboia', 'Beauty', 'https://clinicabiancasaboia.vercel.app', 'rose'],
  ['soulzen', 'Soulzen', 'Wellness', 'https://soulzen-three.vercel.app', 'sage'],
  ['login-laser-tag', 'Login Laser Tag', 'Entertainment', 'https://loginlasertag.vercel.app', 'laser'],
  ['hotel-umu', 'Hotel Umu', 'Hospitality', 'https://hotel-umu-demonstracao.vercel.app', 'gold'],
  ['casa-da-alcacova', 'Casa da Alcáçova', 'Hospitality', 'https://casa-de-alcacova-demonstracao.vercel.app', 'stone'],
]

export const content = {
pt: {
  seo:{title:'Kovelo Studio — Desenvolvimento Web & Experiências Digitais',description:'Kovelo Studio cria websites e experiências digitais à medida, combinando design, desenvolvimento, performance e tecnologia.'},
  nav:{home:'Início',services:'Serviços',projects:'Projetos',about:'Sobre nós',contact:'Contacto',start:'Começar um projeto',menu:'Abrir menu',language:'Alterar idioma'},
  common:{studio:'Experiências digitais',viewWork:'Ver projetos',viewProject:'Ver projeto',live:'Projeto ao vivo',back:'Voltar',next:'Continuar',previous:'Voltar',edit:'Editar respostas',explore:'Explorar serviços',all:'Todos'},
  home:{hero:'Código com visão.|Design com impacto.',intro:'Desenvolvemos experiências digitais à medida para marcas que querem destacar-se.',tags:['Desenvolvimento web','UI / UX','Performance','SEO','Experiência digital'],manifesto:'Não criamos apenas websites.|Criamos experiências digitais.',manifestoCopy:'Acreditamos que um website deve comunicar, envolver e transformar a forma como uma marca é percebida. Unimos estratégia, design e desenvolvimento para criar experiências rápidas, memoráveis e feitas à medida.',servicesLabel:'O que construímos',work:'Projetos selecionados.',workCopy:'Projetos reais. Experiências construídas à medida.',difference:'Precisão por|design.',playground:'Isto não é|um template.',playCopy:'Explore. Cada interação tem uma intenção.',cta:'Pronto para criar|o que vem a seguir?',ctaCopy:'Vamos transformar a sua próxima ideia numa experiência digital.'},
  services:{hero:'Construímos|para a web.',intro:'Design, tecnologia e estratégia reunidos numa experiência digital construída para o seu negócio.',items:[['Desenvolvimento web à medida','Sites desenvolvidos à medida, sem depender de templates genéricos.'],['UI / UX design','Interfaces bonitas, intuitivas e fáceis de utilizar.'],['Performance & SEO','Experiências rápidas, tecnicamente sólidas e preparadas para pesquisa.'],['Manutenção & suporte','Continuamos presentes depois do lançamento.']]},
  process:{label:'Como construímos',title:'Da intenção|ao impacto.',items:[['Descobrir','Entendemos o negócio, público e objetivos.'],['Desenhar','Criamos a experiência visual e a estrutura.'],['Desenvolver','Transformamos o conceito em produto digital.'],['Lançar','Testamos, otimizamos e colocamos no ar.']]},
  pillars:[['Performance','Experiências rápidas e otimizadas.'],['SEO','Estrutura preparada para ser encontrada.'],['Design à medida','Cada projeto começa do zero.'],['Segurança','Boas práticas até ao lançamento.']],
  projects:{hero:'Projetos|selecionados.',intro:'Projetos reais. Experiências construídas à medida.',filters:['Todos','Beauty','Wellness','Entertainment','Hospitality'],descriptions:['Experiência digital para uma marca de estética avançada, combinando serviços, autoridade e conversão.','Uma experiência digital centrada em bem-estar, apresentação do espaço, serviços e marcação.','Uma experiência digital criada para uma marca de entretenimento, com impacto visual e ação.','Experiência digital para hotelaria, criada para apresentar o espaço e facilitar a descoberta.','Uma experiência digital inspirada na identidade histórica e na atmosfera da Casa da Alcáçova.'],detail:'Visão geral do projeto',detailCopy:'Uma experiência digital personalizada, construída para comunicar a identidade da marca com clareza e intenção.'},
  contact:{hero:'Vamos construir|algo.',intro:'Conte-nos um pouco sobre o seu projeto. Queremos perceber o seu negócio, os seus objetivos e o que pretende construir.',steps:['Sobre si','Projeto','Investimento','Prazo','Revisão'],about:'Primeiro, fale-nos sobre si.',name:'Nome completo',email:'E-mail profissional',company:'Empresa / projeto',website:'Website atual',aboutHint:'Se já possui um website, podemos analisá-lo antes da nossa conversa.',project:'O que vamos construir?',projectQuestion:'Qual é o principal objetivo deste projeto?',projectTypes:['Criar um website de raiz','Redesign / atualização de website','E-commerce','Landing page de alta conversão','Outro'],description:'Fale-nos sobre o seu projeto',placeholder:'Conte-nos sobre o seu negócio, o que pretende melhorar e o que gostaria que o novo website fizesse por si...',investment:'Vamos falar de investimento.',investmentCopy:'Esta informação ajuda-nos a preparar uma proposta adequada ao que pretende construir.',budgetQuestion:'Qual é o orçamento estimado?',budgets:['Menos de €1.000','€1.000 – €2.500','€2.500 – €5.000','Mais de €5.000'],timeline:'Quando quer lançar?',timelineQuestion:'Qual é o prazo ideal?',timelines:['O mais rapidamente possível','Dentro de 1–2 meses','Mais de 2 meses / sem urgência','Ainda não tenho uma data'],review:'O seu projeto.',submit:'Solicitar consulta gratuita',required:'Este campo é obrigatório.',invalidEmail:'Introduza um e-mail válido.',select:'Selecione uma opção.',unconfigured:'O envio ainda não está configurado. Guarde as informações e contacte-nos por e-mail.',failed:'Não foi possível enviar. Tente novamente.'},
  thanks:{title:'Projeto|recebido.',body:'Obrigado por confiar na Kovelo Studio. Recebemos as informações do seu projeto e vamos analisá-las antes da nossa conversa.',next:'Quer avançar já para o próximo passo?',book:'Marcar uma conversa de 15 min',pending:'O link de agendamento será disponibilizado em breve.'},
  about:{hero:'Não somos apenas|mais um estúdio.',intro:'A Kovelo é um estúdio digital independente que junta pensamento, design e tecnologia para construir presenças digitais com intenção.',approach:'Como pensamos.',values:[['Clareza antes de ruído','Cada projeto começa por entender o que realmente importa.'],['Design que orienta','A estética cria atenção; a experiência cria confiança.'],['Tecnologia com propósito','O código existe para tornar a ideia mais útil, rápida e viva.']]},
  footer:'Experiências digitais, construídas de forma diferente.',
  copyright:'© 2026 KOVELO STUDIO. Todos os direitos reservados.'
},
en: {
  seo:{title:'Kovelo Studio — Web Development & Digital Experiences',description:'Kovelo Studio creates custom websites and digital experiences through design, development, performance and technology.'},
  nav:{home:'Home',services:'Services',projects:'Projects',about:'About',contact:'Contact',start:'Start a project',menu:'Open menu',language:'Change language'},
  common:{studio:'Digital experiences',viewWork:'View our work',viewProject:'View project',live:'Live project',back:'Back',next:'Continue',previous:'Back',edit:'Edit answers',explore:'Explore services',all:'All'},
  home:{hero:'Code with vision.|Design with impact.',intro:'We build custom digital experiences for brands that want to stand out.',tags:['Web development','UI / UX','Performance','SEO','Digital experience'],manifesto:"We don't just build websites.|We build digital experiences.",manifestoCopy:'A website should communicate, engage and reshape how a brand is perceived. We bring strategy, design and development together to build fast, memorable experiences with purpose.',servicesLabel:'What we build',work:'Selected work.',workCopy:'Real projects. Custom-built experiences.',difference:'Precise by|design.',playground:'This is not|a template.',playCopy:'Move through it. Every interaction has an intention.',cta:"Ready to build|what's next?",ctaCopy:"Let's turn your next idea into a digital experience."},
  services:{hero:'We build|for the web.',intro:'Design, technology and strategy brought together in a digital experience built around your business.',items:[['Custom web development','Websites made to measure, never dependent on generic templates.'],['UI / UX design','Interfaces that are striking, intuitive and easy to use.'],['Performance & SEO','Fast, technically sound experiences prepared for search.'],['Maintenance & support','We stay involved after launch to keep everything working well.']]},
  process:{label:'How we build',title:'From intent|to impact.',items:[['Discover','We understand the business, audience and objectives.'],['Design','We shape the visual experience and structure.'],['Build','We turn the concept into a digital product.'],['Launch','We test, optimise and put it live.']]},
  pillars:[['Performance','Fast, optimised experiences.'],['SEO','A structure prepared to be found.'],['Custom design','Every project starts from zero.'],['Security','Good practice from build to launch.']],
  projects:{hero:'Selected|work.',intro:'Real projects. Custom-built experiences.',filters:['All','Beauty','Wellness','Entertainment','Hospitality'],descriptions:['A digital experience for an advanced aesthetics brand, combining services, authority and conversion.','A wellness-led digital experience built around the space, services and booking journey.','A digital experience for an entertainment brand, focused on visual impact and action.','A hospitality experience designed to present the space and make the hotel easier to discover.','A digital experience inspired by the historic identity and atmosphere of Casa da Alcáçova.'],detail:'Project overview',detailCopy:'A tailored digital experience, designed to express the brand identity with clarity and intention.'},
  contact:{hero:"Let's build|something.",intro:'Tell us about your project. We want to understand your business, your goals and what you want to build.',steps:['About you','Project','Investment','Timeline','Review'],about:'First, tell us about you.',name:'Full name',email:'Professional email',company:'Company / project',website:'Current website',aboutHint:'If you already have a website, we can review it before our conversation.',project:'What are we building?',projectQuestion:'What is the main goal for this project?',projectTypes:['Build a website from scratch','Redesign / update an existing website','E-commerce','High-converting landing page','Other'],description:'Tell us about your project',placeholder:'Tell us about your business, what you would like to improve and what the new website should do for you...',investment:"Let's talk investment.",investmentCopy:'This helps us prepare a proposal that suits what you want to build.',budgetQuestion:'What is your estimated budget?',budgets:['Less than €1,000','€1,000 – €2,500','€2,500 – €5,000','More than €5,000'],timeline:'When do you want to launch?',timelineQuestion:'What is your ideal timeline?',timelines:['As soon as possible','Within 1–2 months','More than 2 months / no rush',"I don't have a date yet"],review:'Your project.',submit:'Request a free consultation',required:'This field is required.',invalidEmail:'Enter a valid email address.',select:'Please select an option.',unconfigured:'Submission is not configured yet. Please save your details and contact us by email.',failed:'We could not send your request. Please try again.'},
  thanks:{title:'Project|received.',body:'Thank you for trusting Kovelo Studio. We have received your project details and will review them before our conversation.',next:'Want to take the next step now?',book:'Book a 15-minute call',pending:'The booking link will be available soon.'},
  about:{hero:'Not just another|digital studio.',intro:'Kovelo is an independent digital studio bringing thought, design and technology together to build digital presences with intention.',approach:'How we think.',values:[['Clarity before noise','Every project begins by understanding what matters.'],['Design that leads','Aesthetics earn attention; experience earns trust.'],['Technology with purpose','Code exists to make an idea more useful, faster and alive.']]},
  footer:'Digital experiences, built differently.',
  copyright:'© 2026 KOVELO STUDIO. All rights reserved.'
}}

export const projectBase = sharedProjects
